#include "../rtstft.h"

const rt_command_define_t cmd_table[RT_CMD_ALL_COMMANDS_COUNT]
    = {{"gain",
        RT_MANIP_GAIN,
        &rt_parser_execute_gain,
        2,
        {RT_CMD_CHAN_RANGE_T, RT_CMD_FLOAT_T},
        1,
        {{'c', 3, {RT_CMD_FLOAT_T, RT_CMD_FLOAT_T, RT_CMD_FLOAT_T}}}},
       {"gate",
        RT_MANIP_GATE,
        &rt_parser_execute_gate,
        2,
        {RT_CMD_CHAN_RANGE_T, RT_CMD_FLOAT_T},
        1,
        {{'c', 3, {RT_CMD_FLOAT_T, RT_CMD_FLOAT_T, RT_CMD_FLOAT_T}}}},
       {"limit",
        RT_MANIP_LIMIT,
        &rt_parser_execute_limit,
        2,
        {RT_CMD_CHAN_RANGE_T, RT_CMD_FLOAT_T},
        1,
        {{'c', 3, {RT_CMD_FLOAT_T, RT_CMD_FLOAT_T, RT_CMD_FLOAT_T}}}},
       {"rebase", RT_MANIP_FLAVOR_UNDEFINED, &rt_parser_execute_rebase},
       {"transpose",
        RT_MANIP_FLAVOR_UNDEFINED,
        &rt_parser_execute_transpose,
        1,
        {RT_CMD_INT_T},
        2,
        {{'c', 1, {RT_CMD_FLOAT_T}}, {'s', 1, {RT_CMD_FLOAT_T}}}}};